# Generated by Django 5.2.6 on 2025-09-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BALL', 'Ball'), ('BOOT', 'Football Boots'), ('KIT', 'Kits & Jerseys'), ('EQUI', 'Equipment'), ('ACCS', 'Accessories'), ('OTHR', 'Other Football Items')], default='OTHR', max_length=20),
        ),
    ]
